### ISSUE TITLE
SystemStackError when using "Remember Me" cookie.

### ISSUE THREAD

**Issue by postmodern** [jm81/dm-devise#7] opened 2010-12-27 23:44 UTC
I noticed that when using the "Remember Me" feature, upon returning to the site I get a SystemStackError. After using ruby-debug, I traced the looping method down.

https://gist.github.com/754008

**Comment by jm81** [comment] 2010-12-29 03:24
I haven't been able to reproduce but I assume it's because #to_time returns self if offset is other than 0, and dm-devise delegates #gmtime to #to_time. It occurred to me that just using DateTime's #new_offset method should accomplish the same without the potential for a loop. However, since I haven't reproduced the bug, I'm not certain this will fix it. Could you give this commit a try and let me know if it works: jm81/dm-devise@8112ccfae585f996de20c5bf5276a9a2f024347a. Thanks

**Comment by djcas9** [comment] 2010-12-29 22:49
That appears to fix the issue in my environment. Thanks jm81

**Comment by jm81** [comment] 2011-01-05 16:58
Closing

**Closed as completed by jm81** 2011-01-05 16:58 UTC
